"""create dim_date table

Revision ID: c2b39704ef6f
Revises: 
Create Date: 2026-05-17 18:55:05.263543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b39704ef6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('calendar_quarter', sa.Integer(), nullable=False),
    sa.Column('calendar_month', sa.Integer(), nullable=False),
    sa.Column('calendar_month_name', sa.String(length=20), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_name', sa.String(length=20), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('is_month_end', sa.Boolean(), nullable=True),
    sa.Column('is_quarter_end', sa.Boolean(), nullable=True),
    sa.Column('is_year_end', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_date')
    # ### end Alembic commands ###
